### ISSUE TITLE
design review v2.4

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/EiBotBoard#1]
Nice work on this! After running the checklist, I found some minor things. Here is my summary/issues:

1) Does the frame have the proper CC attribution? (Frame- Letter/Ledger, CC 4.0) [NO]
comment: exception for v3.0 and old frame

2) Are there any 4-way junctions? [YES]
comment: right side of IC4

3) Are dashed grey lines ('info' eagle layer 97) used to clearly separate different areas? [NO]
comment: If Brian S. really wants it to stay on "guide" layer I suppose it could, but standard layer is "info"

4) Does every part have a NAME and VALUE (with proper prefix and no '$')? [NO]
comment: ICs should be U1, U2, U3

5) Is the LED color standard followed? (red for power, blue for STAT, green for TX, yellow for RX) [NO]
comment: The User LED is kindof a stat, so shouldn't it be blue?

6) Is trace routing up to spec? (to/from center-points, straight lines, 45 angles, 'T' intersections, no right angles or acid traps) [NO]
comment: acid trap coming off left pad of trimpot

7) Are all QFN components with 6 or more leads 75 percent pasted? [NO]
comment: Just talked to Bob and concurred that we should move to a paste comparable to ioio TPS chip, please use A4983ALT1_REDUCED_PASTE

8) Is there a correct version number in the copper? [NO]
comment: Not sure if it's an issue, but your revision note says 4/25/2015, and copper says 4/1/2015, also do we want to go with v24 in copper?

9) Are the board dimensions on 0.05 inch or 0.01 inch grid? [NO]
comment: I guess it's fine that this be slightly off the .05 inch grid, but bottom left should still be set to 0,0

10) Is the SparkFun Logo on the board? [YES]
comment: bottom side logo currently getting chopped a bit by barrel jack

11*) I was wondering if it was discussed with Brian S. about populating the remaining servo connectors with male 0.1 headers?

12*) Any more thoughts on adding silk to show min/max on the current trim pot?

**Comment by EmbeddedMan** [comment]
Pete,

Thanks - all great comments. I'll address them one by one:

1) I do not want to release this as CC 4.0. I ask that SparkFun respect my
wishes and not change the licence on my board. Thanks for granting me an
exception.

2) I was not aware that 4-way junctions are bad ideas. What's the reason
these are to be avoided?

3) Oops. My bad. You are quite correct - info is better than guide. I will
correct and push an update.

4) Good catch. I'll update this as well.

5) The EBB has always had red/green LEDs. Changing colors now is not a good
idea because it invalidates any existing documentation for this product. If
we were just starting this design, I'd be OK with going blue.

6) From the research I've been able to do, acid traps are something that
mattered years ago when etching processes were not as well controlled as
they are today. I'm not aware of any reason why this is a bad idea today -
if you know otherwise, please point me in the direction of the research
that shows this. (Our PCB layout guys at Logic PD - very experienced and
well respected - taught me this about acid traps.)

7) Not being familiar enough with your process, I don't have a comment on
this one. You need to do what you need to do to make it reflow properly.

8) I've had several back and forth e-mails with various SparkFun employees
over the years about version numbers. I always argued for putting a version
number on the board somewhere, and I was told you guys don't like putting
version numbers on the board. I put them on the EBB silk because I felt
they were a good idea. I'm fine with having a version number somewhere on
the board, and in a copper layer is fine by me as long as it is also on the
silk. I will change the copper text to be the same as the silk text, and
all should be 2.4 I believe. Let me know if this isn't a good resolution to
your issue.

9) Cool. Not a problem. - I will update the board to be 2.20" x 2.20" and
then the lower left will be at 0,0.

10) I don't see how the bottom Sparkfun logo could be obscured by the
barrel jack - the barrel jack is on the top side of the board, and none of
the logo overlaps with the barrel jack holes. If you'd like it moved, I
don't mind at all - I'm just not quite sure how to resolve this issue.
Maybe you mean the SparkFun logo on the top side? I can nudge that guy a
bit.

11) Honestly, I'd rather have all 8 RC servo connections populated. Even
better would be to have all I/O (J5 and J5) populated with male headers
sticking up. That way nobody would have to solder connectors in to use any
of those features.

12) Frankly I gave up on trying to accurately portray MIN/MAX on the silk,
because the pot part got changed several times (without revving the board)
on the Easy Driver, and each time the pot was in the opposite direction as
the silk. So users were confused for a significant portion of the Easy
Driver's life. If you can commit to using only pots that respect the
MIN/MAX direction that we put on the silk, I'd be really happy to add it
back in to EBB (And Easy Driver and Big Easy Driver).  But having no silk
is better than having it wrong, I've found, from a support perspective. (I
always just tell people to get their DMM out and monitor the voltage at TP3
anyway.)

*Brian

**Comment by lewispg228** [comment]
Hi Brian,
Thanks for your quick and thorough response!

2) 4-ways leave the opportunity for a net to be drawn "underneath" the node (allowing for two separate net lines to "look" connected). Although this same problem can occur with 3-ways, it is less likely that a designer would draw in an "accidental" node. In fact, we discourage any designer to use the node tool, and only allow nodes to form (automatically) when you intentionally connect two net wires.

5) okay

6) Thanks for your input. I will bring this up at the next engineering meeting, and maybe we will no longer require avoiding acid traps.

8) Please keep version in top silk and change "date code" in bottom copper to "v24" (Date codes usually indicate super old pcb designs, and could cause some confusion)

10) The Bstop of the barrel jack pad is just barely cutting into the "a" of the sparkfun logo. might as well nudge it up a bit to clear the bstop.

11) Thanks for your input. We will look into the cost increase and let you know about any potential price increase. 

On the topic of PTH population, it is also worth mentioning that we are going to shift this onto our selective solder machine and so the headers JP19 and JP20 will be filled in with solder (as is). If you need them to remain open, then they will need to be scooted downward and away from the screw terminal pads at least 0.02 inch. (This is so the fountain of solder can access the screw terminal pads without also filling in the nearby pads)

12) We will commit to using the correct part. Silk will be helpful for our techs during production testing too.

**Comment by EmbeddedMan** [comment]
Pete,

Fantastic.

2) Oh, you meant in the SCHEMATIC! Of course. Those are super bad. I try to
always check for those. Thanks for catching this one. I'll fix it right
away.

8) Cool, will do. Bottom copper will get v24, as will top silk.

10) Ahh, I see the problem now. I was looking at the version-v23 branch,
not the version-v24 branch. I'm now looking at the same files you are.
Sorry! Yup, I can fix that problem.

As for JP19 and JP20, I think it's fine that they're filled with solder. I
don't mind that at all. Will that cause a problem for you when you program
the CPU?

12) OK, so what is the exact part you'll be using so that I can create the
proper silk screen labels?

Thanks-

*Brian

**Comment by EmbeddedMan** [comment]
Pete,

OK, I've now updated the schematic and board with all of the changes we
talked about above.

I noticed that Toni changed the LED colors around from what all previous
EBBs have been. Is there any way we could change these back? I'd rather not
need to have two sections in the documentation "If you have a version made
by Sparkfun v2.4 or later, yoru LED colors will be different . . .". It
would be better if we could keep the two direction LEDs red, the USB LED
green, and the power LED red. I understand this goes against your internal
standards, but this board was designed before I was made aware of those
standards (or I would have followed them for sure).

I did not change the LED colors back - I'll let you guys decide if that's
something you can make an exception for nor not.

So the only thing on your list that's left is the labeling of MIN/MAX for
the trimpot. Once you send me the part number I can look up the datasheet
and add the right silk text.

*Brian

**Comment by lewispg228** [comment]
Hey Brian,
Thanks for your updates. Looks good.

I will ask about the LEDs. Just to be clear, you want same as before right?:
PWR: RED
DIR1: RED
DIR2: RED
USB: GREEN
USR: RED

The new dimension line you have drawn is too thin. Our fab house likes to have this line be 0.008 inch width. You can also remove the outline on tplace, this is unnecessary.

Please update the packages on the driver QFN chips to the package in our library (The only difference is paste aka tcream): 
A4988ALT1_REDUCED_PASTE

We need to dig a little deeper into this trim pot issue. It looks like we have 4 options as suppliers in our system. I will let you know what we find.

**Comment by ToniCorinne** [comment]
Sorry to be late joining this conversation. In the middle of currently fixing all of the Arduino libraries. Brian, do you want to update the package for the QFN chips, or would you prefer I do that? Also Pete, I believe we addressed the trim pot issue on the last revision of the Big Easy Driver (as Brian mentioned, this has been a huge support issue in the past and that was something tech support really pushed for). If you're already digging through all of that information, I'd check the info we have for the B.E.D. trim pot.

**Comment by EmbeddedMan** [comment]
Toni/Pete,

I'm fine making the changes (wider dimension line, removing outline on
tplace, and updating the two driver chips). I'll take care of them when I
get home from work tonight.

Pete-

Yes, you have the LED colors correct. Thanks-

*Brian

**Comment by lewispg228** [comment]
Thanks Brian. That sounds good.

Also, we are cool with making an exception about the LED colors. Please swap them back when you work on the design tonight, and please ensure to use the following two parts in the SparkFun-LED library:

LED-RED0603 (LED-RED) - note the attribue PROD_ID DIO-00819
LED-GREEN0603 (LED-GREEN) - note the attribue PROD_ID DIO-00821

**Comment by EmbeddedMan** [comment]
Quick find on acid traps:
http://electronics.stackexchange.com/questions/115653/are-acid-traps-real-2014

Summary: acid traps may possibly still be an issue if you're using really
really cheap Chinese board vendors. Some US board houses still flag them as
errors however.

*Brian

**Comment by EmbeddedMan** [comment]
OK, all changes as specified above have been made and pushed to GitHub.
Give it a quick check to make sure I didn't forget anything, and then I
think we're good to go except for the pot issue.

*Brian

**Comment by lewispg228** [comment]
Hi Brian,
Here is the info on the trimpot. I have confirmed with our purchasing that we will continue to only buy this exact part from Future. And if we ever need to get a substitute supplier or part, then it will go through our standard substitute verification (which will also involve you, as this is a collaboration).

BI Technologies, manufacturer # 22AR10KLFTR

http://www.futureelectronics.com/en/technologies/passives/resistors/variable-resistors/Pages/7624471-22AR10KLFTR.aspx?IM=0

http://www.bitechnologies.com/pdfs/22.pdf

Please update the silk to indicate MIN/MAX. Then I will verify all changes, and we'll get some protos on order!

PS. Thanks for the links about acid traps. It's good to read some other peoples experience. I will definitely forward it on to our engineering group. Although our fab house (in China) does good work, I would not say they are the best available. In fact, they are the cheapest we can find. We notice a lot of "X"'d out boards (usually in the 1-2% range). Although this is good that they catch any boards with errors during electrical flying probe testing, it's wasteful. Not only with the materials we have to throw in the E-waste, but also our time pasting additional panels to meet our build quantities. I don't know if the X'd out boards were caused by acid traps, cold joints, accidental jumpers, or just fabrication mistakes, but anything we can do to minimize this, I'm all for. 

I like the user, Daniel's, answer about spending 10 minutes at the end of a layout to clean them up, or even better, avoid making them while doing the layout. Being in the QC world, I always think 10 more minutes on a design is worth it - even to avoid a sub-1% error in production, but that's why I'm in QC I suppose :)

**Comment by EmbeddedMan** [comment]
Pete/Toni,

OK, current adjust max direction is now indicated on top silk layer.

Let me know if there is anything else you'd like done!

Thanks-
*Brian

**Comment by lewispg228** [comment]
Hey Brian, Sorry for the delay in my response here. I just had my first kid on 5/3, and I'm just now getting back into the office. Little Graham came two weeks early, so I was a little flustered and didn't finish up this review.

Your latest commit looks good. We'll move forward with prototype of v24. Thanks for all your work on this Brian. This rev is going to be a great improvement!

@ToniCorinne, can you please get the BOM and Assembly sheet updated to include the necessary headers to populate all 8 RC servo connections and all I/O (J5 and J5) populated with male headers sticking up

**Comment by ToniCorinne** [comment]
Assembly has been updated and these are officially out for protos.

**Comment by EmbeddedMan** [comment]
Yes! Thanks so much to both of you - I'm really excited for this updated
EBB version.

*Brian

On Wed, May 20, 2015 at 6:05 PM, Toni Klopfenstein <notifications@github.com
